### ISSUE TITLE
Chinese Edition will be finished soon.

### ISSUE THREAD

**Issue by 0xMashiro** [amusi/machine-learning-yearning-cn#2]
欢迎你合理引用中文翻译的相关内容，遵守版权文件说明：
https://github.com/AcceptedDoge/machine-learning-yearning-cn

**Comment by amusi** [comment]
嗯，考虑到版权问题，我这边一直没有放出来翻译版本。请问如何可以将自己整理的资料放到github上？

**Comment by 0xMashiro** [comment]
非商业转载需要引用原翻译地址（ https://accepteddoge.github.io/machine-learning-yearning-cn/ ）、注明原作者且不可擅自进行内容的二次演绎，商业用途需要联系 deeplearning.ai 官方，此书的中文官方翻译预计于国庆期间完成全部内容，敬请期待。将样稿或者译稿资料打包上传至 Github 的行为并不被提倡，但是还是会有许多人这样做...
